const DIRECTORY_ERROR_CODES = {
  PARENT_DIRECTORY_NOT_FOUND: "PARENT_DIRECTORY_NOT_FOUND",
  DIRECTORY_ACCESS_DENIED: "DIRECTORY_ACCESS_DENIED",
  ROOT_DIRECTORY_CANNOT_BE_DELETED: "ROOT_DIRECTORY_CANNOT_BE_DELETED",
  DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
  ROOT_DIRECTORY_CANNOT_BE_UPDATED: "ROOT_DIRECTORY_CANNOT_BE_UPDATED",
};

const USER_ERROR_CODES = {
  STORAGE_INCREMENT_FAILED: "STORAGE_INCREMENT_FAILED",
  STORAGE_DECREMENT_FAILED: "STORAGE_DECREMENT_FAILED",
};

const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAIN_VIOLATION: "P2002",
  RECORD_NOT_FOUND: "P2025",
};

const FILE_ERROR_CODES = {
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_ALREADY_DELETED: "FILE_ALREADY_DELETED",
};

const SUPABASE_ERROR_CODES = {
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_DELETE_FAILED: "FILE_DELETE_FAILED",
  SIGNED_URL_FAILED: "SIGNED_URL_FAILED",
};

const MULTER_ERROR_CODES = {
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
};

const REGISTER_ERROR_CODES = {
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
};

const LOGIN_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
};

export {
  DIRECTORY_ERROR_CODES,
  LOGIN_ERROR_CODES,
  PRISMA_ERROR_CODES,
  REGISTER_ERROR_CODES,
  FILE_ERROR_CODES,
  SUPABASE_ERROR_CODES,
  MULTER_ERROR_CODES,
  USER_ERROR_CODES,
};
