const DIRECTORY_ERROR_CODES = {
  PARENT_DIRECTORY_NOT_FOUND: "PARENT_DIRECTORY_NOT_FOUND",
  DIRECTORY_ACCESS_DENIED: "DIRECTORY_ACCESS_DENIED",
  ROOT_DIRECTORY_CANNOT_BE_DELETED: "ROOT_DIRECTORY_CANNOT_BE_DELETED",
  DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
  ROOT_DIRECTORY_CANNOT_BE_UPDATED: "ROOT_DIRECTORY_CANNOT_BE_UPDATED",
};

const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAIN_VIOLATION: "P2002",
  RECORD_NOT_FOUND: "P2025",
};

const REGISTER_ERROR_CODES = {
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
};

const LOGIN_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
};

export {
  DIRECTORY_ERROR_CODES,
  LOGIN_ERROR_CODES,
  PRISMA_ERROR_CODES,
  REGISTER_ERROR_CODES,
};
