const MAX_FILES_COUNT_PER_UPLOAD = 10;

const VALID_FILENAME_REGEX = /^[a-zA-Z0-9_\-. ]+$/;

const MAX_FILENAME_LENGTH = 32;

export {
  MAX_FILES_COUNT_PER_UPLOAD,
  VALID_FILENAME_REGEX,
  MAX_FILENAME_LENGTH,
};
