const MAX_FILES_COUNT_PER_UPLOAD = 10;

const MAX_TOTAL_SIZE = 5 * 1024 * 1024;

const VALID_FILENAME_REGEX = /^[a-zA-Z0-9_\-. ]+$/;

const MAX_FILENAME_LENGTH = 32;

export {
  MAX_FILES_COUNT_PER_UPLOAD,
  MAX_TOTAL_SIZE,
  VALID_FILENAME_REGEX,
  MAX_FILENAME_LENGTH,
};
